-- AXLE_LUA_End_ESP32_DaHuan_Debug.lua
-- ESP32 + MG90S custom gripper protocol, adapted from DaHuan V10.
-- TX -> DelayMs(10) -> RX, matching DaHuan.
-- IwdgTaskHandle() stays only in main loop.
-- RX parsing follows DaHuan EndRxGripData() convention.
-- TX CRC generated by Lua; RX CRC not manually rechecked.

local RESPONSE_WAIT_MS = 10
LastTransportError = 0
LastRxMeta = nil

-- WRITE registers
local T1  = {0x01,0x06,0x01,0x00,0x00,0x01,0x00,0x00} -- initialize
local T2  = {0x01,0x06,0x01,0x03,0x00,0x00,0x00,0x00} -- position
local T3  = {0x01,0x06,0x01,0x04,0x00,0x00,0x00,0x00} -- speed
local T4  = {0x01,0x06,0x01,0x01,0x00,0x00,0x00,0x00} -- force placeholder
local T11 = {0x01,0x06,0x01,0x05,0x00,0x01,0x00,0x00} -- execute

-- READ registers
local T5  = {0x01,0x03,0x02,0x00,0x00,0x01,0x00,0x00} -- ready
local T6  = {0x01,0x03,0x02,0x01,0x00,0x01,0x00,0x00} -- motion done
local T7  = {0x01,0x03,0x02,0x02,0x00,0x01,0x00,0x00} -- position
local T8  = {0x01,0x03,0x02,0x03,0x00,0x01,0x00,0x00} -- error
local T9  = {0x01,0x03,0x02,0x04,0x00,0x01,0x00,0x00} -- speed
local T10 = {0x01,0x03,0x02,0x05,0x00,0x01,0x00,0x00} -- force

local function IsIntegerInRange(value, maximum)
    return type(value)=="number" and value>=0 and value<=maximum and value%1==0
end

local function SendAndReceive(T,id)
    LastTransportError=240
    T[1]=id
    T[7],T[8]=CrcValue(T[1],T[2],T[3],T[4],T[5],T[6])
    EndTxGripData(T[1],T[2],T[3],T[4],T[5],T[6],T[7],T[8])
    DelayMs(RESPONSE_WAIT_MS)
    local A,b1,b2,b3,b4,b5,b6,b7,b8=EndRxGripData()
    LastRxMeta=A
    return A,b1,b2,b3,b4,b5,b6,b7,b8
end

local function WriteRegister(T,id,value)
    if not IsIntegerInRange(value,65535) then LastTransportError=242 return false end
    T[6]=value%256
    T[5]=(value-T[6])/256
    local A,b1,b2,b3,b4,b5,b6,b7,b8=SendAndReceive(T,id)

    -- DaHuan write behavior: FC06 is returned to controller.
    if b1==nil or b2==nil then LastTransportError=240 return false end
    if b1~=id or b2~=0x06 then LastTransportError=240 return false end
    if b3~=nil and b3~=T[3] then LastTransportError=240 return false end
    if b4~=nil and b4~=T[4] then LastTransportError=240 return false end

    LastTransportError=0
    GripStateBack(b2)
    return true
end

local function ReadRegister(T,id,maximum)
    local A,b1,b2,b3,b4,b5,b6,b7,b8=SendAndReceive(T,id)

    -- Follow DaHuan convention: A==8, ID, FC03, byte count 02.
    if A~=8 then LastTransportError=240 return nil end
    if b1~=id then LastTransportError=240 return nil end
    if b2~=0x03 then LastTransportError=240 return nil end
    if b3~=0x02 then LastTransportError=240 return nil end
    if b4==nil or b5==nil then LastTransportError=240 return nil end

    local value=b4*256+b5
    if value>maximum then LastTransportError=242 return nil end
    LastTransportError=0
    return value
end

local function ReadAndFeedback(T,id,maximum)
    local value=ReadRegister(T,id,maximum)
    if value~=nil then GripStateBack(value) end
end

while(1) do
    IwdgTaskHandle()
    MainLoop()
    UpDownLoadHandle()
    SdoRwPara()
    EndErrClear()

    local BFlag=LuaBreak()
    if BFlag==1 then break end

    local Rcmd1,Rcmd2,Rcmd3,Rcmd4=GetGripCmd()
    if Rcmd1==1 then
        DelayMs(3)

        if Rcmd3==0x01 then
            WriteRegister(T11,Rcmd2,1)
        elseif Rcmd3==0x02 then
            WriteRegister(T1,Rcmd2,1)
        elseif Rcmd3==0x03 then
            if IsIntegerInRange(Rcmd4,100) then WriteRegister(T2,Rcmd2,Rcmd4)
            else LastTransportError=242 end
        elseif Rcmd3==0x04 then
            if IsIntegerInRange(Rcmd4,100) then WriteRegister(T3,Rcmd2,Rcmd4)
            else LastTransportError=242 end
        elseif Rcmd3==0x05 then
            if Rcmd4==0 then WriteRegister(T4,Rcmd2,0)
            else LastTransportError=242 end
        elseif Rcmd3==0x07 then
            ReadAndFeedback(T6,Rcmd2,1)
        elseif Rcmd3==0x08 then
            ReadAndFeedback(T5,Rcmd2,1)
        elseif Rcmd3==0x09 then
            ReadAndFeedback(T8,Rcmd2,255)
        elseif Rcmd3==0x0A then
            ReadAndFeedback(T7,Rcmd2,100)
        elseif Rcmd3==0x0B then
            ReadAndFeedback(T9,Rcmd2,100)
        elseif Rcmd3==0x0C then
            ReadAndFeedback(T10,Rcmd2,0)
        else
            LastTransportError=243
        end
    end
    LuaGc()
end